name: CI

on:
  push:
    branches:
     - main
     - next
     - 'v*'
    paths-ignore:
      - 'docs/**'
      - '*.md'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '*.md'

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
    group: "${{ github.workflow }}-${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
    cancel-in-progress: true

permissions:
  contents: read

jobs:
  quality-check:
    uses: fastify/workflows/.github/workflows/nested-quality.yml@v6
    permissions:
      contents: read
    secrets: inherit
    with:
      license-check: true
      lint: true

  browsers:
    name: Test Browsers
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Check out repo
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          check-latest: true
          node-version: lts/*

      - name: Install dependencies
        run: npm i

      - name: Install Playwright
        run: npx playwright install

      - name: Run tests
        run: npm run test:browser

  test:
    name: Test
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      matrix:
        node-version: [20, 22, 24]
    steps:
      - name: Check out repo
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          check-latest: true
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm i --ignore-scripts

      - name: Run tests
        run: npm run test:unit

  typescript:
    name: Test TypeScript
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Check out repo
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          check-latest: true
          node-version: lts/*

      - name: Install dependencies
        run: npm i --ignore-scripts

      - name: tsd
        run: npm run test:typescript

  automerge:
    name: Automerge Dependabot PRs
    if: >
        github.event_name == 'pull_request' &&
        github.event.pull_request.head.repo.full_name == github.repository &&
        github.event.pull_request.user.login == 'dependabot[bot]'
    needs: [browsers, quality-check, test, typescript]
    permissions:
      pull-requests: write
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: fastify/github-action-merge-dependabot@30c3f8f14a4f7b315ba38dbc1b793d27128fef82 # v3.12.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          target: major
